### ISSUE TITLE
VALUE ERROR if ⎕SE.Link.U.UCMD_List is not defined

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/link#203] opened 2021-01-14 10:38 UTC
**Describe the bug**
If the v2.1 user command file is installed according to the installation instructions, but the rest of the source code is not in place yet, a VALUE ERROR occurs when starting APL. 

**Expected behaviour**
It would be very helpful to trap this error, explain that the wrong version or no version of Link seems to be installed, and return an empty list of user commands.

`⎕SE.Link.Version`: [2.1.0-beta27]

**Additional context**
This happened to 2/2 users trying to follow the installation instructions today (Morten and Romilly).

**Comment by nicolas-dyalog** [comment] 2021-01-14 12:39
Fixed in 2.1.0-beta29

**Comment by nicolas-dyalog** [comment] 2021-01-14 13:16
Morten thinks the fix can be improved:

    It contains a hardcoded URL, and there is a risk that we will want to change this. We want this code to never ever EVER have to change again, because it causes serious grief each time it changes.

    The message says Link User Commands are not correctly installed, which leads the user astray: the cause of the problem is that Link itself that is not correctly installed, the user command IS correctly installed.

**Comment by nicolas-dyalog** [comment] 2021-01-14 14:23
Fixed in Link v2.1.0-beta30

**Comment by abrudz** [comment] 2021-01-14 14:28
Will `Please follow installation instructions from the Link help to install Link properly` not immediately cause the question about where to find this help?

**Comment by mkromberg** [comment] 2021-01-20 07:33
I agree with Adam's comment, the comment to please install properly is unnecessary. Also, testing shows that the committed fix does not actually work, you cannot return ⍬ from List. I will submit a pull request later today.

**Closed** 2021-01-20 12:17 UTC
Labels: bug
