### ISSUE TITLE
⎕SE.Link.Expunge crashes on scalars

### ISSUE THREAD

**Issue by aplteam** [Dyalog/link#387] opened 2021-10-22 15:57 UTC
**Describe the bug**
```
⊣⎕SE.Link.Expunge 'q'
```
results in a RANK ERROR.

**Comment by mkromberg** [comment] 2021-11-02 09:02
I am unable to reproduce this in Link 3.0.8. Which version are you using?

**Comment by aplteam** [comment] 2021-11-02 16:44
3.0.8!

Did you really try the API function? The user command works.

**Comment by mkromberg** [comment] 2021-11-02 17:37
Yes, I did. But I had not created a Link, as the repro didn't mention that this was necessary ;-).

**Comment by mkromberg** [comment] 2021-11-04 08:56
Fixed in v3dev branch, awaiting review before commit to master.

**Closed** 2021-12-14 14:50 UTC
Labels: bug
