### ISSUE TITLE
Expunge retuns a result that is different from what Fix returns

### ISSUE THREAD

**Issue by aplteam** [Dyalog/link#265] opened 2021-05-15 07:42 UTC
`Fix` returns 1 if the object in question is linked and otherwise 0, and that makes perfect sense.
Shouldn't `Expunge` do precisely the same for the sake of consistency? 

Currently it returns a boolean telling whether the object was expunged or not (like `⎕EX`), something I never found useful.

BTW, the documentation of `Expunge` needs some polishing.

**Comment by nicolas-dyalog** [comment] 2021-05-24 12:47
Yup. Link.Expunge and Link.Fix have different "designs".
Expunge is a full replacement for ⎕EX, meaning you can replace any call to ⎕EX by a call to Link.Expunge to make your code Link-compatible.
Link.Fix is NOT a full replacement for ⎕FIX because it won't do anything if the name is not in a linked directory.
The good question is : do they have different designs by design ?

**Comment by aplteam** [comment] 2021-05-25 05:10
Nope. It was rather decided that Fix should be a general replacement for the built-in system functions `⎕FX` and `⎕FIX`.

**Comment by nicolas-dyalog** [comment] 2021-05-25 11:05
Fixed in link v2.1.0-beta89

**Closed by nicolas-dyalog** 2021-05-25 11:05 UTC
Labels: bug
