### ISSUE TITLE
]Link.Create #andys should error   (note: no characters between "#" and "andys")

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/link#269] opened 2021-06-01 09:12 UTC
]Link.Create #andys
Linked: # → /home/andys/#andys

Leaving me with the rather nastily named directory '#andys' ..  think that expression should error as it should have 2 arguments.

      ]version
 Dyalog  18.1.40612 64-bit Unicode, BuildID f71cd074
 OS      Linux 4.15.0-142-generic #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021 x86_64
 Link    2.1.0-beta88
 SALT    2.9
 UCMD    2.5
 .NET
 WS      18.1

**Comment by dyaandys** [comment] 2021-06-01 09:56
As Kai pointed out to me, you can have great fun by passing *andys or andys* as the single argument .. be careful getting rid of the resulting directory :-)

**Comment by nicolas-dyalog** [comment] 2021-06-03 12:15
A - The first behaviour is correct : 
A1 - The namespace is unspecified to it defaults to current namespace which is #
A2 - All that is specified is the directory name "#andys", and so ]link.create does what it's told
If you expect UCMDs to parse APL, and scan "#" separately from "andys" in "#andys", then we need to redesign the whole UCMD framework which assumes that space is the argument separator.

B - Can you describe the exact repro, what goes wrong, and what you would have expected as a result ?
My understanding of your sarcastic description of the problem is to attempt to do "]link.create andys*", which correctly fails for me on windows, and correctly succeeds on linux.

**Comment by aplteam** [comment] 2021-06-03 14:02
Then the help needs polishing. The only indicator that it may be called with just one argument is this:

```
Syntax: 1-2 arguments (last arguments merged) 
```

And because the help lists `<ns>`as the  first, one would assume that the second one (the directory) is optional. Which is most probably the reason why Andy drew the conclusion that `Create` requires two arguments.

And BTW what `last arguments merged` means is a mystery to me.

**Comment by abrudz** [comment] 2021-06-03 14:12
IIRC, we decided to assume # for the single-argument case, only for the
user command. Maybe indeed that was a bad shortcut. Should we roll it back?

last arguments merged means that you can have (single) spaces in the last
argument, and they won't be treated as separate arguments. Useful when the
last argument is a path which may contain spaces.

**Comment by mkromberg** [comment] 2021-06-04 07:27
I don't remember the discussions. Apparently we disallow it in the API function and in hindsight it certainly seems like a bad idea to allow it in the user command. 

]link.create should require two arguments.

**Comment by nicolas-dyalog** [comment] 2021-06-04 10:59
Reverted Q6 of #136.
Fixed in link v2.1.0-beta92

**Closed by nicolas-dyalog** 2021-06-04 10:59 UTC
Labels: bug
