### ISSUE TITLE
Link.Refresh # gives a mysterious syntax error if there is nothing to synchronize

### ISSUE THREAD

**Issue by dyavc** [Dyalog/link#95] opened 2019-09-24 12:22 UTC
)clear
]link.create # d:\tmp\junklink\
]link.Refresh #
* Command Execution Failed: SYNTAX ERROR

I then )ed and fix a function and then this works.
)ed blah
      ]link.Refresh #

Linked: # ←→ d:\tmp\junklink

      ]uversion Link.refresh
framework:  2.4                                                                      
command:    ]LINK.Refresh                                                            
source:     C:\Program Files\Dyalog\Dyalog APL-64 17.1 Unicode\SALT\spice\Link.dyalog
version:    2.09                                                                     
revision:                                                                            
commit:     2019 06 19 Adam: Avoid special-cased vars in caller

**Comment by abrudz** [comment] 2019-11-11 15:35
I cannot reproduce this with user command version 2.12 and c293d59d358cd381b7befb15720d122cb400cd14 — @stampes can you?

**Comment by stampes** [comment] 2019-11-11 15:41
```
      ]uversion Link.refresh
framework:  2.3                                                                   
command:    ]LINK.Refresh                                                         
source:     \\dk01sn017\IMSDEV\Dev\Common\Dyalog\Production\SALT\spice\Link.dyalog
version:    2.09                                                                  
revision:                                                                         
commit:     2019 06 19 Adam: Avoid special-cased vars in caller                   
                                                                                  
             )clear
clear ws

      ]link.create # c:\tmp\junklink
Source directory not found: c:\tmp\junklink
      ]link.create # c:\tmp\junklink
Linked: # ←→ c:\tmp\junklink

      ]link.Refresh #
* Command Execution Failed: SYNTAX ERROR

      )ed ee
      ]link.Refresh #
Linked: # ←→ c:\tmp\junklink
```
Like this?

**Comment by abrudz** [comment] 2019-11-11 15:46
No, please try upgrading Link to c293d59 and see it that helps.

**Comment by stampes** [comment] 2019-11-11 16:05
```
R:\Dev\Common\Dyalog\LSVCLONE>git status
HEAD detached at c293d59
```
       ]uversion Link.refresh
framework:  2.4                                                                 
command:    ]LINK.Refresh                                                       
source:     \\dk01sn017\IMSDEV\Dev\Common\Dyalog\LSVCLONE\SALT\spice\Link.dyalog
version:    2.09                                                                
revision:                                                                       
commit:     2019 06 19 Adam: Avoid special-cased vars in caller                 
                                                                                



      )clear
clear ws

      ]link.create # d:\tmp\junklink
Source directory not found: d:\tmp\junklink
]link.Refresh #
* Command Execution Failed: SYNTAX ERROR
```

**Comment by abrudz** [comment] 2019-11-11 16:20
So can I close this issue?

**Comment by stampes** [comment] 2019-11-11 17:08
So vi take the release defined as  c293d59d358cd381b7befb15720d122cb400cd14 and use?

**Comment by abrudz** [comment] 2019-11-11 17:14
Yes, or in other words, use the 17.1 branch.

**Comment by nicolas-dyalog** [comment] 2020-05-08 14:58
closed then.

**Closed by nicolas-dyalog** 2020-05-08 14:58 UTC
Labels: bug, critical
