### ISSUE TITLE
LENGTH ERROR on ]link.create

### ISSUE THREAD

**Issue by bpbecker** [Dyalog/link#118] opened 2020-05-01 13:01 UTC
1. Clone the Dyalog/DUI repository (let's say to /git/dui/)
2. ]link.create # /git/dui

Results in a LENGTH ERROR

**Comment by abrudz** [comment] 2020-05-01 13:15
The problem is in FixFiles:
```apl
             nss←U.DotSlash¨paths/⍨~'.'∊¨paths            ⍝ transform simple dirs into nss
             nss←StripCaseCode nss
```
should be something like
```apl
             paths/⍨←~'.'∊¨paths
             nss←U.DotSlash¨paths
             nss←StripCaseCode nss
```

**Comment by nicolas-dyalog** [comment] 2020-05-07 10:43
Fixed in Link v2.1

**Closed by nicolas-dyalog** 2020-05-07 10:43 UTC
