### ISSUE TITLE
Edit window captions of linked objects can be wrong

### ISSUE THREAD

**Issue by aplteam** [Dyalog/link#275] opened 2021-07-26 16:24 UTC
**Describe the bug**

While editing a linked object the window caption tells that the object lives in `#` even if it lives in a sub-namespace

**Expected behaviour**

When editing the same object unlinked it shows the parent namespace, and that's how it should be.

**Desktop (please complete the following information):**
 - OS: Windows
 - APL version: 18.0 Unicode 64-bit
 - `⎕SE.Link.Version`: 2.1.0-beta94

**Comment by mkromberg** [comment] 2021-09-02 10:55
This will be fixed soon in Dyalog versions 18.0 and later. The issue is logged as

0019295: )ed of a function with external source does not show the namespace that the function is in

**Closed by mkromberg** 2021-09-02 10:55 UTC
Labels: bug
