### ISSUE TITLE
Link 3.0 docs website can show a blank menu on the left 

### ISSUE THREAD

**Issue by dyavc** [Dyalog/link#346] opened 2021-09-15 14:22 UTC
On the Link 3.0 docs website, 

Make sure that your window width is not too wide, maybe half your screen or less.

using the mouse, I went to 

3 bars menu

I did not see Working with Link so i clicked the Left arrow in the menu to go up/back

Then, I clicked on  Working with Link

I pressed page down and ended up with a blank menu

MS windows 10,  Google Chrome  Version 93.0.4577.63 (Official Build) (64-bit).  Also, have updated Chrome twice and I can still reproduce it.  (Chrome is up to date  Version 94.0.4606.71 (Official Build) (64-bit))

Does not happen in Firefox or Edge.
![blankleft2](https://user-images.githubusercontent.com/15029839/133451399-ecfcb36f-0197-4bc7-a5ae-587c21a8461a.jpg)

**Comment by dyavc** [comment] 2021-09-16 08:20
Now, I think Google Chrome may have fixed itself on my PC.  (now Version 93.0.4577.82 (Official Build) (64-bit))

I no longer get the 3 bars menu button, and so I cannot repro this issue either now.

**Comment by mbaas2** [comment] 2021-09-16 08:59
Hi Vince,
the 3bars menu button is shown when your screen width goes below a certain limit. I was able to repro that problem once, but not a second time. So there definitely is something not working as expected, but finding a reliable repro seems to be the challenge ;) (I'll reopen - maybe we can find a repro)

**Comment by dyavc** [comment] 2021-09-16 09:13
Thanks Michael, that was exactly the case!  

Now, with a less wide window, it happens to me all the time.

**Comment by dyavc** [comment] 2021-10-05 14:47
This happens in the office as well, so is not related to running under Remote Desktop.  My Windows 10 DPI is 125%

**Comment by mkromberg** [comment] 2021-12-21 10:45
This problem is hard to reproduce and appears to be an issue with the [mkdocs/material](https://squidfunk.github.io/mkdocs-material/) theme. I am closing this until we have a more easily reproducible case that we could report to squidfunk.

**Closed by mkromberg** 2021-12-21 10:45 UTC
Labels: documentation
