### ISSUE TITLE
:Require doesn't work

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/link#170] opened 2020-11-04 07:18 UTC
**Describe the bug**
If a folder contains two files:

server.apln:

:Require file://engine.apln
:Namespace server
   dup←#.engine.dup
:EndNamespace

and

engine.apln:

:Namespace engine
   dup←{⍵ ⍵}
:EndNamespace

`            ]link.create # c:\tmp\linktest`
`Linked: # ←→ c:\tmp\linktest; 1 import(s) failed (⎕SE.Link.Links[1].inFail)`

`      ⎕SE.Link.Links[1].inFail`
` c:/tmp/linktest/server.apln`

**Expected behaviour**
These two files should load cleanly.

**Desktop (please complete the following information):**
 - OS: Windows
 - APL version: 19.0.39491
 - `⎕SE.Link.Version`: 2.1.0-alpha

**Comment by nicolas-dyalog** [comment] 2020-11-05 14:25
duplicate of #155
fixed in link v2.1

**Closed by nicolas-dyalog** 2020-11-05 14:25 UTC
Labels: bug
