### ISSUE TITLE
]LINK.Create does not create links in a )CLEAR ws

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/link#161] opened 2020-10-20 12:23 UTC
**Describe the bug**
]LINK.Create does not create links in a )CLEAR ws.

**To Reproduce**
Steps to reproduce the behaviour:
1. use master-branch of LINK-repo
2. start v18
3. clone https://github.com/Dyalog/library-core or download it (_the problem is not specific to that repro, I actually encountered it for the 1st time with another repo)_
4. ]LINK.create # /git/library-core

Error-message:
Cannot link a non-empty namespace to a non-empty directory: #.# ←→ /git/library-core

**Expected behaviour**
I'd like to see a link established to that source-folder.

**Screenshots**
![image](https://user-images.githubusercontent.com/5645494/96585317-b47c8b00-12df-11eb-96ca-e1bc157b7dd2.png)

**Session transcript**
see above.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - APL version: 18u64.39262
 - `⎕SE.Link.Version`: 2.1.0-alpha

**Comment by nicolas-dyalog** [comment] 2020-10-20 14:38
Can't reproduce.
     ]link.create # /home/nicolas/Downloads/library-core-master
Linked: # ←→ /home/nicolas/Downloads/library-core-master

Can you confirm that there is nothing in your # ? 
0∊⍴#.⎕NL-⍳10  ⍝ should return 1

**Comment by mbaas2** [comment] 2020-10-20 14:49
Yep:

```
      0∊⍴#.⎕NL-⍳10 ⍝ should return 1 
1

```

**Comment by mbaas2** [comment] 2020-10-20 14:58
Oh, Options >Object-Syntax > Expose... explains the difference. I had all 3 set - if I disable them, it works!

**Comment by nicolas-dyalog** [comment] 2020-10-21 13:52
Fixed in Link v2.1

**Closed by nicolas-dyalog** 2020-10-21 13:52 UTC
Labels: bug
