### ISSUE TITLE
]link.add multiple names

### ISSUE THREAD

**Issue by rikedyp** [Dyalog/link#213] opened 2021-01-25 14:29 UTC
WIBNI I could do
`]Link.Add var1 var2 fn1 fn2`
etc.
It seems as if this funtionality exists in the API, but not in the UCMD
StartupSession/Link/Add.aplf
```APL
      ⎕SE.Link.Add'var1' 'var2' 'fn'
Added: #.var1 #.var2 #.fn
```

**Comment by abrudz** [comment] 2021-01-25 14:47
Duplicate of #194

**Closed by abrudz** 2021-01-25 14:47 UTC
Labels: enhancement
