### ISSUE TITLE
]link attempts for ⎕fix any changed files it sees, errors get logged to status-window

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/link#164] opened 2020-10-23 12:33 UTC
**Describe the bug**
I noticed a confusing behaviour while I was working on a project: as the code was executed, the status-window was flooded with error-msgs relating to a data-file of the app.

**To Reproduce**
Steps to reproduce the behaviour:
      1. 3 ⎕mkdir'c:\temp\newDir'
      2. ]link.create # c:\temp\newDir
     3. (⊂';some text')⎕nput 'c:\temp\newDir\foo.ini'

**Expected behaviour**
This is an .ini-file - ]link is not expected to do anything with it, so it should not even try to do so.

**Content of status-window**
```
line(0,0) : error AC0120: assignment is not permitted outside of a :Class or :Namespace ";some text" 
                                                                                         ^
Complete: 1 error.
line(0,0) : error AC0120: assignment is not permitted outside of a :Class or :Namespace ";some text" 
                                                                                         ^
Complete: 1 error.

```

**Desktop (please complete the following information):**
 - OS: Win10
 - APL version: 180u64.39262
 - `⎕SE.Link.Version`: 2.1.0-alpha

**Comment by nicolas-dyalog** [comment] 2020-10-27 09:46
That's a duplicate of #149 - link may output spurious status messages when sniffing files.

In this very case, Link could indeed not sniff the file at all, at the cost of unnecessary code complexity.

Link doesn't do anything else than sniffing the file, it then decides to ignore the file due to its extension. Set ⎕SE.Link.DEBUG←1 to see :
`Notify: created /tmp/link164/foo.ini: file extension not managed by link`
So there is no side effect to the user, apart from spurious output to the session as decscribed by issue #149

**Closed by nicolas-dyalog** 2020-10-27 09:46 UTC
Labels: bug
