### ISSUE TITLE
Under some circumstances renaming a function has strange effects

### ISSUE THREAD

**Issue by aplteam** [Dyalog/link#392] opened 2021-11-03 10:16 UTC
**Describe the bug**

After renaming a function `Foo` into `Goo` when I edit again `Foo`, `Goo` is displayed.

**To Reproduce**

1. Load the attached workspace
2. Edit, say, `Link_Tests.Test_Create_001` and change the name. I added a couple of trailing underscores.
3. Press ESCAPE to fix the function
4. Edit again `Link_Tests.Test_Create_001`  - you see the renamed function instead

This happens only when the namespace `#.Link_Tests` was linked to a folder, and I break the link before saving the workspace.

**Expected behaviour**

When I attempt to edit `Foo` I expect to see `Foo`.

**Screenshots**

I've uploaded a video.

**Desktop (please complete the following information):**
```
]tooLS.Version
 Dyalog  18.0.44659 64-bit Unicode, BuildID beef5c8d            
 OS      Windows 10 or Windows Server 2016 (10.0.19043) 64-bit  
 Link    3.0.8                                                  
 SALT    2.808                                                  
 UCMD    2.51                                                   
 .NET    .NET Framework 4.8.4420.0                              
 WS      18.0                                                   
```

This is my <01934>

https://user-images.githubusercontent.com/16479389/140042407-7e9958b8-4c12-4a27-9144-a9116de2d7f5.mp4

The workspace: [1934.zip](https://github.com/Dyalog/link/files/7466748/1934.zip)

**Comment by mkromberg** [comment] 2021-12-14 16:51
Closing the Link issue after logging interpreter issue "0019566: After making a copy of a 2 ⎕FIX'd function, )ed opens the wrong function" against 18.0. I was not able to reproduce this in 18.2.

**Closed by mkromberg** 2021-12-14 16:51 UTC
Labels: bug
