### ISSUE TITLE
]link.create with forcefilenames and casecode creates an aplf file with the wrong filename

### ISSUE THREAD

**Issue by dyavc** [Dyalog/link#232] opened 2021-03-04 15:11 UTC
**Describe the bug**
]link.create with forcefilenames and casecode creates an aplf file with the wrong filename

**To Reproduce**
)ns #.Selektor
)ns #.Selektor.Meldung
)ed #.Selektor.Meldung.Meldung

⍝⍝⍝Now we create a link :
]Link.Create #.Selektor d:/temp/Selektor -source=ns  -watch=ns -casecode -forcefilenames

result :  picture1.png
folder Meldung-1 contains Meldung.Meldung-401.aplf

**Expected behaviour**
if do not use -forcefilenames, the file is named Meldung-1.aplf

**Screenshots**

**Session transcript**
If applicable, copy your log in to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 10.0.19041 Build 1904
 - APL version: 18.0.40044 Classic 32-bit 
 - `⎕SE.Link.Version`: 2.1.0-beta51

**Additional context**

**Comment by nicolas-dyalog** [comment] 2021-03-08 14:28
Duplicate of issue #231

**Closed by nicolas-dyalog** 2021-03-08 14:28 UTC
Labels: bug
