### ISSUE TITLE
Changing the name of a function while tracing causes confusion

### ISSUE THREAD

**Issue by aplteam** [Dyalog/link#288] opened 2021-08-26 11:24 UTC
1. Trace into any existing function
2. Invoke the editor
3. Make some changes
3. Change the name of the function
4. Press "Escape" in order to fix the newly introduced function

At this this point without Link being involved the Tracer would switch back to the originally function which is correct.

When the function is Linked the Tracer will continue to show the newly introduced function which is wrong.

**Desktop (please complete the following information):**
```
Dyalog  18.0.44280 64-bit Unicode, BuildID fb98f1e4            
 OS      Windows 10 or Windows Server 2016 (10.0.19043) 64-bit  
 SALT    2.808, Link: 2.1.0-beta94                              
 UCMD    2.51                                                   
 .NET    .NET Framework 4.8.4400.0                              
 WS      18.0                                                   
```

**Comment by mkromberg** [comment] 2021-09-02 11:43
This is not related to Link as such, it will be fixed soon in Dyalog versions 18.0 and later. The issue is logged as

0019296: Changing a function with external source in the tracer leads to incorrect tracer display

**Closed by mkromberg** 2021-09-02 11:43 UTC
Labels: bug
