### ISSUE TITLE
Link 4.0 ignored "watch"

### ISSUE THREAD

**Issue by aplteam** [Dyalog/link#589] opened 2023-09-16 07:36 UTC
**Describe the bug**

I established a Link with watch=NS, yet when I copy an APL source file into the linked folder I get (I have `NOTIFY←1`):

```
Link @ 09:31: Updated ⎕SE.SessionExtensions.Cider.OS (C:/Users/kai/Documents/Dyalog APL-64 19.0 Unicode Files/StartupSession/SessionExtensions/Cider/OS.aplc)
```

When I delete the file from the folder I get

```
Link @ 09:31: Deleted ⎕SE.SessionExtensions.Cider.ADOC_uc (C:/Users/kai/Documents/Dyalog APL-64 19.0 Unicode Files/StartupSession/SessionExtensions/Cider/ADOC_uc.dyalog)
```

When I copy it again I get --- nothing!

**Comment by mkromberg** [comment] 2023-09-16 18:17
I suspect that an earlier error / failed QA run / etc / left a live FSW behind, looking at the folder. I am unable to reproduce it and will close this in a few days unless it is possible to provide reproduction instructions.

**Comment by mkromberg** [comment] 2023-09-21 06:59
I am closing this until we have a repro - there is nothing we can do at the moment.

**Closed by mkromberg** 2023-09-21 06:59 UTC
Labels: bug
