### ISSUE TITLE
Spurious warning doing Link.Add on a namespace

### ISSUE THREAD

**Issue by aplteam** [Dyalog/link#280] opened 2021-08-04 06:30 UTC
After calling `Create` on `Foo` I did:

```
'Vars'#.Foo.⎕ns''
#.Foo.Vars.a←1
```

When I now call `]Link.ReSync` I get 

```
1 change must be resolved by hand before -proceed is possible
```

This is wrong: I did not specify `-array`, therefore `#.Foo.Vars.a` should be ignored.

**Comment by mkromberg** [comment] 2021-08-28 18:54
When I attempt to recreate this, I see:

      ]link.create anapp c:\tmp\anapp
Linked: #.anapp ←→ c:\tmp\anapp
      'Vars' anapp.⎕NS ''
      anapp.Vars.life←42
      ]link.resync
1 updates required                                                  
NOTE: 1 changes must be resolved by hand before -proceed is possible
                                                                    
 Name          Direction  File  Comments                            
 #.anapp.Vars  ?                item has no corresponding file      

This seems reasonable: you created a namespace using ⎕NS and a corresponding folder needs to be created. This has nothing to do with the existence of the variable within it.

You can fix this with:

      ]link.add anapp.Vars
Added: #.anapp.Vars

Currently, this results in a pointless warning when the filesystem watcher reports that there is a new folder, I will be looking into that:

Link Warning: ⎕SE.Link.Notify: created c:/tmp/anapp/Vars: ignoring attempt to redefine #.anapp.Vars which is linked to c:/     tmp/anapp/Vars/

**Comment by mkromberg** [comment] 2021-08-29 07:56
It turned out this was simply caused by not removing the trailing slash when comparing the changed folder name to the one that Link was expecting. PR submitted.

**Closed** 2021-08-31 08:07 UTC
Labels: bug
