### ISSUE TITLE
Can't link a dfn (when it is named "lc")

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/link#163] opened 2020-10-21 15:44 UTC
**Describe the bug**
I have a dfn in file uc.aplf which does not find its way into the workspace after ]link.create or ]link.import. The counterpart lc.aplf does not have such problems.

**To Reproduce**
Steps to reproduce the behaviour:
1. unzip [lcuc.zip](https://github.com/Dyalog/link/files/5417065/lcuc.zip) to {path}
2. ]link.create # {path}
3. check `⎕nc¨'lc' 'uc'   ⍝ lc undefined!`

**Expected behaviour**
`lc` should be defined just like `uc `is.   There is a chance that I messed up the file - but the lack of any information about `]link `not having done its job completely might worry some users.

**Desktop (please complete the following information):**
 - OS: Win10
 - APL version: 18u64.39262
 - `⎕SE.Link.Version`: 2.1.0-alpha

**Comment by abrudz** [comment] 2020-10-21 16:27
I can reproduce this, but only when linking to `#`, not to a sub-namespace.

**Comment by mbaas2** [comment] 2020-10-23 12:46
It seems that this is somehow related to the name of the fn. If I call it "`xc`" instead, it is handled correctly!

**Comment by mbaas2** [comment] 2020-10-25 09:07
@abrudz: this also affects link 2.0.3!

**Comment by nicolas-dyalog** [comment] 2020-10-27 10:36
Fixed in link v2.1
I suspect the issue reproduces in Link v2.0.3 because when you switch link branches, you forget to update $DYALOG/SALT/spice/link.dyalog from the repository - and the bug was in that file.

**Comment by mbaas2** [comment] 2020-10-27 10:48
I am happy to confirm that it is fixed indeed!
But your theory abt. 2.0.3 was wrong - the error is reproduceable after selecting the 2.0-branch and copying all files.

**Comment by nicolas-dyalog** [comment] 2020-10-27 10:48
Right, it does reproduce in 2.0.3

**Comment by nicolas-dyalog** [comment] 2020-10-27 10:48
Fixed in 2.0.3

**Closed by nicolas-dyalog** 2020-10-27 10:48 UTC
Labels: bug
